version: '3.8'

services:
  nginx:
    image: docker.arvancloud.ir/nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cmd/web:/usr/share/nginx/html:ro
    ports:
      - "80:80"

