service: android-emulator-serverless

frameworkVersion: ^3.38.0

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: go1.x
  stage: local

custom:
  serverless-offline:
    noPrependStageInUrl: true

functions:
  ping:
    handler: bin/ping
    package:
      include:
        - bin/ping
    events:
      - http:
          path: ping
          method: get
  register:
    handler: bin/register
    package:
      include:
        - bin/register
    events:
      - http:
          path: register
          method: post
  login:
    handler: bin/login
    package:
      include:
        - bin/login
    events:
      - http:
          path: login
          method: post
  registerDevice:
    handler: bin/registerDevice
    package:
      include:
        - bin/registerDevice
    events:
      - http:
          path: registerDevice
          method: post
  getDevice:
    handler: bin/getDevice
    package:
      include:
        - bin/getDevice
    events:
      - http:
          path: getDevice
          method: get
  deleteDevice:
    handler: bin/deleteDevice
    package:
      include:
        - bin/deleteDevice
    events:
      - http:
          path: deleteDevice
          method: delete